// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS_System.Models
{
    public partial class Asignacionmaquinaria
    {
        public string Codmaquina { get; set; }
        public string Codcli { get; set; }
        public string Codagencia { get; set; }
        public int? Estadomaquin { get; set; }
        public DateTime? Feccrea { get; set; }
        public string Codusercrea { get; set; }
        public string Codcia { get; set; }
        public int Id { get; set; }
    }
}