// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS_System.Models
{
    public partial class Asignacionprovincias
    {
        public int Id { get; set; }
        public string Coduser { get; set; }
        public string Codcia { get; set; }
        public string Codprov { get; set; }
        public string Codcanton { get; set; }
        public string Codmantenimiento { get; set; }
        public string Codusermod { get; set; }
    }
}