// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS_System.Models
{
    public partial class Empresa
    {
        public string Codcia { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Telf1 { get; set; }
        public string Telf2 { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
    }
}