// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CMS_System.Models
{
    public partial class Imgfile
    {
        public int Id { get; set; }
        public string Codentidad { get; set; }
        public string Urlruta { get; set; }
        public string Tipo { get; set; }
    }
}